In [1]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [2]:
train_data = pd.read_csv("G:/ExcelR_Data/Data_Science_Course/Assignments/Naive Bayes/SalaryData_Train.csv")
train_data.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [3]:
test_data = pd.read_csv("G:/ExcelR_Data/Data_Science_Course/Assignments/Naive Bayes/SalaryData_Test.csv")
test_data.head()

age   workclass      education  educationno        maritalstatus  \
0   25     Private           11th            7        Never-married   
1   38     Private        HS-grad            9   Married-civ-spouse   
2   28   Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44     Private   Some-college           10   Married-civ-spouse   
4   34     Private           10th            6        Never-married   

           occupation    relationship    race    sex  capitalgain  \
0   Machine-op-inspct       Own-child   Black   Male            0   
1     Farming-fishing         Husband   White   Male            0   
2     Protective-serv         Husband   White   Male            0   
3   Machine-op-inspct         Husband   Black   Male         7688   
4       Other-service   Not-in-family   White   Male            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            50   United-States   <=50K  
2            0            40   United-States    >50K  
3            0            40   United-States    >50K  
4            0            30   United-States   <=50K

In [4]:
#Converting categorical values into numeric values for train data
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
train_data["workclass"]=le.fit_transform(train_data["workclass"])
train_data["education"]=le.fit_transform(train_data["education"])
train_data["maritalstatus"]=le.fit_transform(train_data["maritalstatus"])
train_data["occupation"]=le.fit_transform(train_data["occupation"])
train_data["relationship"]=le.fit_transform(train_data["relationship"])
train_data["race"]=le.fit_transform(train_data["race"])
train_data["sex"]=le.fit_transform(train_data["sex"])
train_data["native"]=le.fit_transform(train_data["native"])
train_data["Salary"]=le.fit_transform(train_data["Salary"])
train_data.head(2)

age  workclass  education  educationno  maritalstatus  occupation  \
0   39          5          9           13              4           0   
1   50          4          9           13              2           3   

   relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  \
0             1     4    1         2174            0            40      37   
1             0     4    1            0            0            13      37   

   Salary  
0       0  
1       0

In [5]:
#Converting categorical values into numeric values for test data
test_data["workclass"]=le.fit_transform(test_data["workclass"])
test_data["education"]=le.fit_transform(test_data["education"])
test_data["maritalstatus"]=le.fit_transform(test_data["maritalstatus"])
test_data["occupation"]=le.fit_transform(test_data["occupation"])
test_data["relationship"]=le.fit_transform(test_data["relationship"])
test_data["race"]=le.fit_transform(test_data["race"])
test_data["sex"]=le.fit_transform(test_data["sex"])
test_data["native"]=le.fit_transform(test_data["native"])
test_data["Salary"]=le.fit_transform(test_data["Salary"])
test_data.head(2)

age  workclass  education  educationno  maritalstatus  occupation  \
0   25          2          1            7              4           6   
1   38          2         11            9              2           4   

   relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  \
0             3     2    1            0            0            40      37   
1             0     4    1            0            0            50      37   

   Salary  
0       0  
1       0

In [6]:
#Splitting data into train and test
x_train = train_data.iloc[:,0:13]
y_train = train_data.iloc[:,13]
x_test  = test_data.iloc[:,0:13]
y_test  = test_data.iloc[:,13]

In [7]:
#Creating model using GaussianNB
model_gnb=GaussianNB()
model_gnb.fit(x_train,y_train)

GaussianNB()

In [8]:
preds1 = model_gnb.predict(x_test)
preds1

array([0, 0, 0, ..., 0, 1, 0])

In [9]:
pd.Series(preds1).value_counts() # getting the count of each category  

0    13250
1     1810
dtype: int64

In [10]:
pd.crosstab(y_test,preds1)  # getting the 2 way table to understand the correct and wrong predictions

col_0       0     1
Salary             
0       10759   601
1        2491  1209

In [11]:
#confusion_matrix
confusion_matrix(y_test,preds1)

array([[10759,   601],
       [ 2491,  1209]], dtype=int64)

In [12]:
# classification_report
from sklearn.metrics import classification_report
print(classification_report(y_test,preds1))

              precision    recall  f1-score   support

           0       0.81      0.95      0.87     11360
           1       0.67      0.33      0.44      3700

    accuracy                           0.79     15060
   macro avg       0.74      0.64      0.66     15060
weighted avg       0.78      0.79      0.77     15060



In [13]:
#Creating model using MultinomialNB
model_mnb=MultinomialNB()
model_mnb.fit(x_train,y_train)

MultinomialNB()

In [14]:
preds2 = model_mnb.predict(x_test)
preds2

array([0, 0, 0, ..., 0, 1, 0])

In [15]:
pd.Series(preds2).value_counts() # getting the count of each category  

0    13811
1     1249
dtype: int64

In [16]:
pd.crosstab(y_test,preds2)  # getting the 2 way table to understand the correct and wrong predictions

col_0       0    1
Salary            
0       10891  469
1        2920  780

In [17]:
#confusion_matrix
confusion_matrix(y_test,preds2)

array([[10891,   469],
       [ 2920,   780]], dtype=int64)

In [18]:
# classification_report
print(classification_report(y_test,preds2))

              precision    recall  f1-score   support

           0       0.79      0.96      0.87     11360
           1       0.62      0.21      0.32      3700

    accuracy                           0.77     15060
   macro avg       0.71      0.58      0.59     15060
weighted avg       0.75      0.77      0.73     15060

